title: SensorVault
url: "https://sensorvault.github.io"
baseurl: ""

remote_theme: startbootstrap/startbootstrap-clean-blog-jekyll

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
